---
permalink: protect/update-credentials.html 
sidebar: sidebar 
keywords: SRA credentials, updating 
summary: Affinché VMware Live Site Recovery possa comunicare con SRA, dovresti aggiornare le credenziali di SRA sul server VMware Live Site Recovery se hai modificato le credenziali. 
---
= Aggiorna le credenziali SRA negli strumenti ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Affinché VMware Live Site Recovery possa comunicare con SRA, dovresti aggiornare le credenziali di SRA sul server VMware Live Site Recovery se hai modificato le credenziali.

.Prima di iniziare
Dovresti aver eseguito i passaggi menzionati nell'argomento link:../protect/configure-on-srm-appliance.html["Configurare SRA sull'appliance VMware Live Site Recovery"].

.Passaggi
. Eseguire i seguenti comandi per eliminare le credenziali degli ONTAP tools memorizzate nella cache dalla macchina VMware Live Site Recovery:
+
.. `sudo su <enter root password>`
.. `docker ps`
.. `docker exec -it <container_id> sh`
.. `cd conf/`
.. `rm -rf *`


. Esegui il comando Perl per configurare SRA con le nuove credenziali:
+
.. `cd ..`
.. `perl command.pl -I --otv-ip <OTV_IP>:8443 --otv-username <OTV_ADMIN_USERNAME> --otv-password <OTV_ADMIN_PASSWORD> --vcenter-guid <VCENTER_GUID>`Devi mettere una singola virgoletta intorno al valore della password.
+
Viene visualizzato un messaggio di conferma dell'avvenuta memorizzazione delle credenziali di archiviazione. SRA può comunicare con il server SRA utilizzando l'indirizzo IP, la porta e le credenziali fornite.







[[reconfigure-vcenter-in-the-vmware-live-site-recovery-appliance-after-a-certificate-change]]
== Riconfigurare vCenter nell'appliance VMware Live Site Recovery dopo una modifica del certificato

Se il certificato vCenter cambia, ad esempio dopo un aggiornamento vCenter, è possibile che si verifichi un errore di mancata corrispondenza dell'impronta digitale nell'estensione Site Recovery. Eseguire i seguenti passaggi per risolverlo.

.Passaggi
. Riconfigurare vCenter nell'appliance VMware Live Site Recovery
+
.. Aprire l'interfaccia di gestione dell'appliance VMware Live Site Recovery in un browser: `\https://<SRM_IP>:5480`
.. Seleziona la scheda *Riepilogo*.
.. Seleziona *Riconfigura* per la connessione al server vCenter.
+
Questo recupera e accetta l'impronta digitale del certificato più recente da vCenter.



. Riconnetti l'associazione del sito (se l'errore persiste)
+
Se l'errore di mancata corrispondenza dell'impronta digitale persiste dopo la riconfigurazione:

+
.. Accedi all'interfaccia utente di vCenter.
.. Accedere all'estensione *Site Recovery*.
.. Individua la sezione *Associazione siti*.
.. Seleziona *Riconnetti* per ristabilire l'associazione del sito con il certificato aggiornato.



