---
permalink: manage/reset-manager-password.html 
sidebar: sidebar 
keywords:  
summary: 'Se hai dimenticato la password di ONTAP tools Manager, puoi reimpostare le credenziali dell"amministratore utilizzando il token generato dalla console di manutenzione di ONTAP tools for VMware vSphere.' 
---
= Reimposta la password di ONTAP tools Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se dimentichi la password di ONTAP tools Manager, puoi ripristinare l'accesso amministratore usando un token di reset generato dalla console di manutenzione di ONTAP tools for VMware vSphere.

.Passaggi
. Apri un browser web e vai su  `https://<ONTAPtoolsIP>:8443/virtualization/ui/` per accedere a ONTAP tools Manager.
. Nella pagina di accesso, seleziona *Reimposta password*.
. Genera un token di reimpostazione della password utilizzando la console di manutenzione di ONTAP tools for VMware vSphere:
+
.. Accedi al vCenter Server e apri la console di manutenzione.
.. Premi Invio `2` per selezionare *Configurazione di sistema*.
.. Premi  `3` per selezionare *Cambia password utente 'maint'*.


. Nella finestra di dialogo per il ripristino della password, inserisci il token di ripristino, il nome utente e la nuova password.
. Seleziona *Ripristina* per aggiornare le credenziali.
. Accedi a ONTAP tools Manager con la nuova password.

